server {
    listen 80;
    listen [::]:80;
    server_name admin.impersia.cloud;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        return 301 https://admin.impersia.cloud$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name admin.impersia.cloud;

    ssl_certificate /etc/letsencrypt/live/admin.impersia.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.impersia.cloud/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /opt/impersia-os/apps/admin/dist;
    index index.html;

    add_header Strict-Transport-Security "max-age=86400" always;
    add_header X-Robots-Tag "noindex, nofollow" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
