server {
    listen 80;
    listen [::]:80;
    server_name impersia.cloud www.impersia.cloud;
    return 301 https://impersia.cloud$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.impersia.cloud;

    ssl_certificate /etc/letsencrypt/live/www.impersia.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.impersia.cloud/privkey.pem;

    return 301 https://impersia.cloud$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name impersia.cloud;

    ssl_certificate /etc/letsencrypt/live/impersia.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/impersia.cloud/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /opt/impersia-os/apps/comercial;
    index index.html;

    add_header Strict-Transport-Security "max-age=86400" always;

    location = /app {
        return 301 /app/;
    }

    location /app/ {
        alias /opt/impersia-os/apps/web/dist/;
        index index.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
